name: Jest test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22"

      - name: Dependencies
        run: npm install

      - name: Run test
        run: npm test